UPDATE shop.product SET SUPPLIER = 'Merc', MODEL = 'GBH 2-24 D', PRICE = 259 WHERE ID = 1;
UPDATE shop.product SET SUPPLIER = 'Posrch', MODEL = 'GBH 2-26 DFR', PRICE = 367 WHERE ID = 2;
UPDATE shop.product SET SUPPLIER = 'Lambor', MODEL = 'GBH 2-28 DFV', PRICE = 376 WHERE ID = 3;
UPDATE shop.product SET SUPPLIER = 'Lada', MODEL = 'GBH 2-24 DRE', PRICE = 309 WHERE ID = 4;